### ISSUE TITLE
Transfer ownership to rust-embedded-community

### ISSUE THREAD

**Issue by MathiasKoch** [rust-embedded-community/serde-json-core#37]
Hi,

I think this would make a perfect fit for the rust-embedded-community organization (https://github.com/rust-embedded-community/), seeing as it currently seems to have stalled the maintenance a bit, and it is in my optic a core crate for embedded IoT.

I already discussed with @eldruin, who agrees its a great fit.

**Comment by eldruin** [comment]
Small correction, I am just one of the organization members. The others have just not set their membership as public.

**Comment by MathiasKoch** [comment]
Ahh, fair enough. Didn't mean to single you out. 

Point was that this didn't mean a lot of additional work for @japaric

**Comment by japaric** [comment]
Happy to transfer this to the rust-embedded-community org if they are OK with taking it.
For now I'll wait until I get a "thumbs up" from one of the rust-embedded-community members.

**Comment by eldruin** [comment]
Alright, sorry for the long delay. Now that it has been settled that the rust-embedded-community will not become a sub-org of rust-embedded I would say this can be transferred.
The motivation for the transfer matches exactly the mission of the rust-embedded-community.

**Comment by MathiasKoch** [comment]
Sounds good!

**Comment by japaric** [comment]
Alright, transferring the repo now!

**Comment by japaric** [comment]
and ...
"You don’t have the permission to create public repositories on rust-embedded-community"

I think I may need to be a member of the org if I want to transfer it directly to the org.
I guess the other option is to transfer it to a member of the org and then that member can transfer it to the org.
@eldruin should we do option (a) or (b)?

**Comment by eldruin** [comment]
I think it would be quickest if you transfer it to me and then I will transfer it to the org.

**Comment by japaric** [comment]
@eldruin done! you should have received an e-mail or notification about the transfer

**Comment by eldruin** [comment]
This is now complete. Thanks @japaric and @MathiasKoch!

**Comment by eldruin** [comment]
One last thing @japaric: Could you grant rust-embedded-community/all team permissions at crates.io?

**Comment by japaric** [comment]
@eldruin invited you as an owner; you can then invite the GH team (I cannot do that without being part of the team)

**Comment by eldruin** [comment]
Thanks! I have invited the team but I guess @thejpster is the one who got the email. Maybe we can setup some redirections or so.
Anyway, we can work like this for now. Thanks again!
