### ISSUE TITLE
Add support for alloc::* types

### ISSUE THREAD

**Issue by Pzixel** [rust-embedded-community/serde-json-core#4]
Currently I have following errors:

```
error[E0277]: the trait bound `alloc::String: serde::Serialize` is not satisfied
  --> C:\Users\Alex\Documents\Repo\pwasm-abi\derive\src\json.rs:14:10
   |
14 | #[derive(Serialize, Debug)]
   |          ^^^^^^^^^ the trait `serde::Serialize` is not implemented for `alloc::String`
   |
   = note: required by `serde::ser::SerializeStruct::serialize_field`
```

Could it be done in no-std scenario?

**Comment by sanmai-NL** [comment]
@Pzixel: the solution would be for `serde_json` to use the `alloc` crate.

**Comment by Pzixel** [comment]
But they clearly say "It won't work, and even if it would, I won't support and/or accept any issues caused by this". It's kinda unstable situation.

**Comment by sanmai-NL** [comment]
Can you please provide a reference to that claim? A crate can be (not `no_std`) + `alloc`. For many operations, the `alloc` equivalents could be used.

**Comment by Pzixel** [comment]
https://github.com/serde-rs/json/issues/463#issuecomment-405388092

> I don't intend to bring no-std support into serde_json as discussed previously in #362.

**Comment by dtolnay** [comment]
I reconsidered and would be willing to consider a serde_json PR to use `alloc`. https://github.com/serde-rs/json/issues/362#issuecomment-431186156

**Comment by jonimake** [comment]
I too would appreciate if the library used alloc crate types if there was an alloc feature enabled. Now I'm forced to use heapless String type instead of the alloc crate String type if I call to_string for example.

**Comment by Xanewok** [comment]
FWIW serde_json should support using only `alloc` via (now merged) https://github.com/serde-rs/json/pull/606

**Comment by jordens** [comment]
AFAICT this can be closed as both not pertinent to `serde-json-core` and resolved in `serde-json`.

**Comment by eldruin** [comment]
Thank you everybody!
