### ISSUE TITLE
This is not real core lib since it depends on serde which is standard library. 

### ISSUE THREAD

**Issue by Jiuhong-casperlabs** [rust-embedded-community/serde-json-core#62]
This is not real core lib since it depends on serde which is standard library.

**Comment by eldruin** [comment]
This is called `-core` because it does not use the Rust standard library.
Closing as non-actionable.

**Comment by ryan-summers** [comment]
I am unsure what issue you are having. This crate is designed to work in a `no_std` environment. If you are having issues with that, please post them here. Posting statements like in the topic and issue body aren't relevant to any particular issue.

To clarify some issues that I suspect you might have (rather, using `serde-json-core` in a `no_std` environment), let me provide some points of clarification:
*  `serde` is not a part of `std`. It is indeed its own crate named [`serde`](https://github.com/serde-rs/serde) that must be specified in the `Cargo.toml` file.
* `serde` can be used without the `std` library, but some default-features need to be enabled.

If you're having issues using this crate or serde in a `no_std` environment, please check out https://serde.rs/no-std.html.
