### ISSUE TITLE
Release please?

### ISSUE THREAD

**Issue by zeenix** [rust-embedded-community/serde-json-core#89]
Hi, Thanks for this super useful crate. I want to use it in our project at work but we're already on heapless 0.8 and would like to avoid having to depend on two versions of that. I see that in the git master branch, heapless is already updated to 0.8. Since it's been slightly more than a year since the last release, could you kindly publish one? :pray:

**Comment by ryan-summers** [comment]
I'd be happy to publish a release once https://github.com/rust-embedded-community/serde-json-core/pull/83 lands. I just haven't had the bandwidth to cotninue with the review yet. I'll try to find some time tomorrow and then generate a release :)
